# Other commands relevant for pip:
# 
#  python setup.py register
#  python setup.py sdist upload

all:
	@echo "Nothin to see here dude."

build:
	python setup.py build

install:
	sudo python setup.py install

distro:
	python setup.py sdist

clean:
	rm -rf build

